start_recirculation:
  name: Start Recirculation
  description: Start recirculation on the water heater.
  target:
    entity:
      domain: water_heater
  fields:
    recirculation_minutes:
      name: Recirculation minutes
      description: The time to recirculate in minutes.
      default: true
      selector:
        select:
          options:
            - 5
            - 15
            - 30
            - 45
            - 60
            - 75
            - 90
            - 105
            - 120
            - 135
            - 150
            - 165
            - 180
            - 195
            - 210
            - 225
            - 240
            - 255
            - 270
            - 285
            - 300
stop_recirculation:
  name: Stop Recirculation
  description: Stop recirculation on the water heater.
  target:
    entity:
      domain: water_heater