name: 🐛 Bug Report
description: Report a bug or issue with the Rinnai Control-R integration
title: "[BUG] "
labels: ["bug", "investigating"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Please search to see if an issue already exists for the bug you encountered.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search the existing issues to see if this has already been reported.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your Home Assistant environment.
      value: |
        - Home Assistant Core version:
        - Integration version:
        - Python version:
        - Install type (HACS, manual):
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output from Home Assistant.
        
        To enable debug logging for this integration, add the following to your configuration.yaml:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.rinnai: debug
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here, such as:
        - Screenshots
        - Device model information
        - Network configuration
        - Recent changes to your setup
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting steps
      description: Please confirm you have tried the following troubleshooting steps.
      options:
        - label: I have restarted Home Assistant
        - label: I have checked the Home Assistant logs for errors
        - label: I have verified my Rinnai Control-R credentials are correct
