name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the Rinnai Control-R integration
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        Please search to see if a similar feature request already exists.

  - type: checkboxes
    id: existing-feature
    attributes:
      label: Is there an existing feature request for this?
      description: Please search the existing issues to see if this has already been requested.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've considered...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case and how this feature would benefit you and other users.
      placeholder: This feature would help me...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or examples about the feature request here.
        
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
